apps/githome_web/lib/githome_web/router.ex
defmodule GithomeWeb.Router do
  use GithomeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NavigationHistory.Tracker
  end

  pipeline :verify do
    plug GithomeWeb.CheckAuth, :verify
  end

  pipeline :main_layout do
    plug :put_layout, {GithomeWeb.LayoutView, :main}
  end

  pipeline :reg_layout do
    plug :put_layout, {GithomeWeb.LayoutView, :reg}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GithomeWeb do
    pipe_through ~w[browser reg_layout]a

    get "/", LoginController, :index
    post "/login", LoginController, :login
    post "/register", LoginController, :register
  end

  scope "/session", GithomeWeb do
    pipe_through ~w[browser verify]a

    get "/new", SessionController, :new
    get "/logout", SessionController, :logout
  end

  scope "/my_projects", GithomeWeb do
    pipe_through ~w[browser main_layout verify]a

    get "/", MyProjectController, :index
    get "/new", MyProjectController, :new
    get "/show", MyProjectController, :show
    get "/edit", MyProjectController, :edit
    get "/view", MyProjectController, :view
    get "/log", MyProjectController, :log
    delete "/delete", MyProjectController, :delete
    post "/create", MyProjectController, :create
    post "/update", MyProjectController, :update
    put "/update", MyProjectController, :update
  end

  scope "/users", GithomeWeb do
    pipe_through ~w[browser main_layout verify]a

    get "/", UserController, :index
    get "/show", UserController, :show
    get "/edit", UserController, :edit
    delete "/delete", UserController, :delete
    get "/new", UserController, :new
    post "/create", UserController, :create
    post "/update", UserController, :update
    put "/update", UserController, :update
    get "/change_password", UserController, :change_password
    post "/change_password", UserController, :change_password_post
    post "/change_admin", UserController, :admin
  end

  scope "/settings", GithomeWeb do
    pipe_through ~w[browser main_layout verify]a

    get "/", ParameterController, :index
    get "/show", ParameterController, :show
    get "/edit", ParameterController, :edit
    delete "/delete", ParameterController, :delete
    get "/new", ParameterController, :new
    post "/create", ParameterController, :create
    post "/update", ParameterController, :update
  end

  scope "/projects", GithomeWeb do
    pipe_through ~w[browser main_layout verify]a

    get "/", ProjectController, :index
    get "/show", ProjectController, :show
    get "/edit", ProjectController, :edit
    delete "/delete", ProjectController, :delete
    get "/new", ProjectController, :new
    post "/create", ProjectController, :create
    post "/update", ProjectController, :update
  end

  scope "/groups", GithomeWeb do
    pipe_through ~w[browser main_layout verify]a

    get "/", GroupController, :index
    get "/show", GroupController, :show
    get "/edit", GroupController, :edit
    delete "/delete", GroupController, :delete
    get "/new", GroupController, :new
    post "/create", GroupController, :create
    post "/update", GroupController, :update
  end

  scope "/my_groups", GithomeWeb do
    pipe_through ~w[browser main_layout verify]a

    get "/", MyGroupController, :index
    get "/show", MyGroupController, :show
    get "/edit", MyGroupController, :edit
    delete "/delete", MyGroupController, :delete
    get "/new", MyGroupController, :new
    post "/create", MyGroupController, :create
    post "/update", MyGroupController, :update
    put "/update", MyGroupController, :update
  end

  #   Other scopes may use custom stacks.
  scope "/api", GithomeWeb do
    pipe_through ~w[api]a
    resources "/", ApiController
  end
end

apps/githome_web/lib/githome_web/controllers/project_controller.ex
defmodule GithomeWeb.ProjectController do
  use GithomeWeb, :controller

  alias Githome.Projects
  alias Githome.Projects.Project
  alias Githome.Users
  alias GithomeWeb.GitController, as: Git

  @exclude_delete ~w[gitolite-admin]

  def index(conn, _params) do
    user = get_session(conn, :user)

        user_update = Users.get_user!(user.id)
        projects = Projects.list_projects()

        conn
        |> put_session(:user, user_update)
        |> put_session(:nav_active, :projects_view_all)
        |> render("index.html",
          projects: projects,
          user: user_update,
          layout: {GithomeWeb.LayoutView, "main.html"},
          nav_active: :projects_view_all,
          admin: user_update.admin,
          exclude_delete: @exclude_delete
        )
  end

  def new(conn, _params) do
    changeset = Projects.change_project(%Project{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"project" => project_params}) do
    case Projects.create_project(project_params) do
      {:ok, project} ->
        user = get_session(conn, :user).username
        pname = project_params.project_name
        Git.create_project(pname, RW: user)

        conn
        |> put_flash(:info, "Project created successfully.")
        |> redirect(to: Routes.project_path(conn, :show, project))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    project = Projects.get_project!(id)
    render(conn, "show.html", project: project)
  end

  def edit(conn, %{"id" => id}) do
    project = Projects.get_project!(id)
    changeset = Projects.change_project(project)
    render(conn, "edit.html", project: project, changeset: changeset)
  end

  def update(conn, %{"id" => id, "project" => project_params}) do
    project = Projects.get_project!(id)

    case Projects.update_project(project, project_params) do
      {:ok, project} ->
        conn
        |> put_flash(:info, "Project updated successfully.")
        |> redirect(to: Routes.project_path(conn, :show, project))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", project: project, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    project = Projects.get_project!(id)
    {:ok, _project} = Projects.delete_project(project)

    conn
    |> put_flash(:info, "Project deleted successfully.")
    |> redirect(to: Routes.project_path(conn, :index))
  end
end

apps/githome_web/lib/githome_web/views/project_view.ex
defmodule GithomeWeb.ProjectView do
  use GithomeWeb, :view
end

apps/githome_web/lib/githome_web/templates/project/edit.html.eex
<h1>Edit Project</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.project_path(@conn, :update, @project)) %>

<span>
    <%= link "Back", to: Routes.project_path(@conn, :index) %></span>

apps/githome_web/lib/githome_web/templates/project/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
<%= if @changeset.action do %>
<div class="alert alert-danger">
    <p>Oops, something went wrong! Please check the errors below.</p>
</div>
<% end %>

<%= label f, :project_name %>
<%= text_input f, :project_name %>
<%= error_tag f, :project_name %>

<div>
    <%= submit "Save" %>
</div>
<% end %>

apps/githome_web/lib/githome_web/templates/project/index.html.eex
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table id="mytable" class="table table-bordred table-striped">
                    <thead>
                        <th>Project Name</th>
                        <th>Description</th>
                        <th>Url</th>
                        <%= if @admin do %>
                        <th>Edit</th>
                        <th>Delete</th>
                        <% end %>
                    </thead>
                    <tbody>
                        <%= for p <- @projects do %>
                        <tr>
                            <td>
                                <%= link p.project_name, to: Routes.my_project_path(@conn, :show, %{"id" => p.id}), class: "btn btn-primary btn-xs"  %>
                            </td>
                            <td>
                                <%= p.description %>
                            </td>
                            <%= if @admin do %>
                            <td>githome@<%= @conn.host %>:<%= p.project_name %>.git</td>
                            <td>
                                <p data-placement="top" data-toggle="tooltip" title="Edit">
                                    <%= link raw(~s(<span class="glyphicon glyphicon-pencil"></span>)), to: Routes.my_project_path(@conn, :edit, %{"id" => p.id}), class: "btn btn-primary btn-xs",
                                        data_title: "Edit", data_toggle: "modal"
                                    %>
                                </p>
                            </td>
                            <td>
                            <%= if p.project_name not in @exclude_delete do %>
                                <p data-placement="top" data-toggle="tooltip" title="Delete">
                                    <%= link raw(~s(<span class="glyphicon glyphicon-trash"></span>)), to: Routes.my_project_path(@conn, :delete, %{"id" => p.id}), class: "btn btn-danger btn-xs",
                                        data_title: "Delete", data_toggle: "modal", method: "DELETE"
                                    %>
                                </p>
                                <% end %>
                            </td>
                            <% end %>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

apps/githome_web/lib/githome_web/templates/project/new.html.eex
<h1>New Project</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.project_path(@conn, :create)) %>

<span>
    <%= link "Back", to: Routes.project_path(@conn, :index) %></span>

apps/githome_web/lib/githome_web/templates/project/show.html.eex
<h1>Show Project</h1>

<ul>

    <li>
        <strong>Project name:</strong>
        <%= @project.project_name %>
    </li>

</ul>

<span>
    <%= link "Edit", to: Routes.project_path(@conn, :edit, @project) %></span>
<span>
    <%= link "Back", to: Routes.project_path(@conn, :index) %></span>