apps/githome_web/lib/githome_web/router.ex
defmodule GithomeWeb.Router do
  use GithomeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NavigationHistory.Tracker
  end

  pipeline :verify do
    plug GithomeWeb.CheckAuth, :verify
  end

  pipeline :main_layout do
    plug :put_layout, {GithomeWeb.LayoutView, :main}
  end

  pipeline :reg_layout do
    plug :put_layout, {GithomeWeb.LayoutView, :reg}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GithomeWeb do
    pipe_through ~w[browser reg_layout]a

    get "/", LoginController, :index
    post "/login", LoginController, :login
    post "/register", LoginController, :register
  end

  scope "/session", GithomeWeb do
    pipe_through ~w[browser verify]a

    get "/new", SessionController, :new
    get "/logout", SessionController, :logout
  end

  scope "/my_projects", GithomeWeb do
    pipe_through ~w[browser main_layout verify]a

    get "/", MyProjectController, :index
    get "/new", MyProjectController, :new
    get "/show", MyProjectController, :show
    get "/edit", MyProjectController, :edit
    get "/view", MyProjectController, :view
    get "/log", MyProjectController, :log
    delete "/delete", MyProjectController, :delete
    post "/create", MyProjectController, :create
    post "/update", MyProjectController, :update
    put "/update", MyProjectController, :update
  end

  scope "/users", GithomeWeb do
    pipe_through ~w[browser main_layout verify]a

    get "/", UserController, :index
    get "/show", UserController, :show
    get "/edit", UserController, :edit
    delete "/delete", UserController, :delete
    get "/new", UserController, :new
    post "/create", UserController, :create
    post "/update", UserController, :update
    put "/update", UserController, :update
    get "/change_password", UserController, :change_password
    post "/change_password", UserController, :change_password_post
    post "/change_admin", UserController, :admin
  end

  scope "/settings", GithomeWeb do
    pipe_through ~w[browser main_layout verify]a

    get "/", ParameterController, :index
    get "/show", ParameterController, :show
    get "/edit", ParameterController, :edit
    delete "/delete", ParameterController, :delete
    get "/new", ParameterController, :new
    post "/create", ParameterController, :create
    post "/update", ParameterController, :update
  end

  scope "/projects", GithomeWeb do
    pipe_through ~w[browser main_layout verify]a

    get "/", ProjectController, :index
    get "/show", ProjectController, :show
    get "/edit", ProjectController, :edit
    delete "/delete", ProjectController, :delete
    get "/new", ProjectController, :new
    post "/create", ProjectController, :create
    post "/update", ProjectController, :update
  end

  scope "/groups", GithomeWeb do
    pipe_through ~w[browser main_layout verify]a

    get "/", GroupController, :index
    get "/show", GroupController, :show
    get "/edit", GroupController, :edit
    delete "/delete", GroupController, :delete
    get "/new", GroupController, :new
    post "/create", GroupController, :create
    post "/update", GroupController, :update
  end

  scope "/my_groups", GithomeWeb do
    pipe_through ~w[browser main_layout verify]a

    get "/", MyGroupController, :index
    get "/show", MyGroupController, :show
    get "/edit", MyGroupController, :edit
    delete "/delete", MyGroupController, :delete
    get "/new", MyGroupController, :new
    post "/create", MyGroupController, :create
    post "/update", MyGroupController, :update
    put "/update", MyGroupController, :update
  end

  #   Other scopes may use custom stacks.
  scope "/api", GithomeWeb do
    pipe_through ~w[api]a
    resources "/", ApiController
  end
end

apps/githome_web/lib/githome_web/controllers/group_controller.ex
defmodule GithomeWeb.GroupController do
  use GithomeWeb, :controller

  alias Githome.GroupInfo.Ginfo
  alias Githome.GroupInfo
  alias Githome.Users

  plug :put_layout, "main.html"

  def index(conn, _params) do
    user = get_session(conn, :user)
    groups = GroupInfo.list_ginfos()
    user_update = Users.get_user!(user.id)

    conn
    |> put_session(:user, user_update)
    |> put_session(:nav_active, :groups_view_all)
    |> render("index.html",
      groups: groups,
      layout: {GithomeWeb.LayoutView, "main.html"},
      user: user_update,
      nav_active: :groups_view_all
    )
  end

  def new(conn, _params) do
    user = get_session(conn, :user)

    changeset = GroupInfo.change_ginfo(%Ginfo{})
    users = Users.list_users()

    list_of_users =
      for %{username: username, id: id} <- users do
        {username, id}
      end

    user_update = Users.get_user!(user.id)

    conn
    |> put_session(:user, user_update)
    |> put_session(:nav_active, :groups)
    |> render("new.html",
      changeset: changeset,
      layout: {GithomeWeb.LayoutView, "main.html"},
      users: list_of_users,
      user: user_update,
      nav_active: :groups,
      token: get_session(conn, :token)
    )
  end

  def create(conn, params) do
    group_params = params["group"]

    case GroupInfo.create_ginfo(group_params) do
      {:ok, group} ->
        conn
        |> put_flash(:info, "Group created successfully.")
        |> redirect(to: Routes.group_path(conn, :show, group))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> render("new.html",
          changeset: changeset,
          layout: {GithomeWeb.LayoutView, "main.html"},
          user: get_session(conn, :user),
          nav_active: :groups,
          token: get_session(conn, :token)
        )
    end
  end

  def show(conn, %{"id" => id}) do
    group = GroupInfo.get_ginfo!(id)
    render(conn, "show.html", group: group)
  end

  def edit(conn, %{"id" => id}) do
    group = GroupInfo.get_ginfo!(id)
    changeset = GroupInfo.change_ginfo(group)
    render(conn, "edit.html", group: group, changeset: changeset)
  end

  def update(conn, %{"id" => id, "group" => group_params}) do
    group = GroupInfo.get_ginfo!(id)

    case GroupInfo.update_ginfo(group, group_params) do
      {:ok, group} ->
        conn
        |> put_flash(:info, "Group updated successfully.")
        |> redirect(to: Routes.group_path(conn, :show, group))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", group: group, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    group = GroupInfo.get_ginfo!(id)
    {:ok, _group} = GroupInfo.delete_ginfo(group)

    conn
    |> put_flash(:info, "Group deleted successfully.")
    |> redirect(to: Routes.group_path(conn, :index))
  end
end

apps/githome_web/lib/githome_web/views/group_view.ex
defmodule GithomeWeb.GroupView do
  use GithomeWeb, :view
end

apps/githome_web/lib/githome_web/templates/group/edit.html.eex
<h1>Edit Group</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.group_path(@conn, :update, @group)) %>

<span>
    <%= link "Back", to: Routes.group_path(@conn, :index) %></span>

apps/githome_web/lib/githome_web/templates/group/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
<%= if @changeset.action do %>
<div class="alert alert-danger">
    <p>Oops, something went wrong! Please check the errors below.</p>
</div>
<% end %>
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <%= label f, :name, class: "col-sm-2 control-label" %>
                <div class="col-md-5">
                    <%= text_input f, :name, placeholder: "Enter group name", class: "form-control input-md"%>
                    <%= error_tag f, :name %>
                    <!--<span class="help-block">help</span>-->
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <label>
                <h4>Select Users</h4>
                <%= multiple_select(f, :members, @users, class: "form-control multiselect multiselect-icon", type: "text", multiple: "multiple", role: "multiselect") %>
            </label>
        </div>
        <div class="col-sm-3">
            <label>
                <h4>Select Projects</h4>
                <%= multiple_select(f, :projects, @users, class: "form-control multiselect multiselect-icon", type: "text", multiple: "multiple", role: "multiselect") %>
            </label>
        </div>
    </div>
    <%= submit "Save", class: "btn btn-success"%>
</div>
<% end %>

apps/githome_web/lib/githome_web/templates/group/index.html.eex
<hr>
<div class="container">
    <div class="row">
        <div class="col-sm-9">
            <h1>All Groups</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table id="mytable" class="table table-bordred table-striped">
                    <thead>
                        <th>Name</th>
                        <th>Owner</th>
                        <%= if @user.admin do %>
                        <th>Edit</th>
                        <th>Delete</th>
                        <% end %>
                    </thead>
                    <tbody>
                        <%= for group <- @groups do %>
                        <% [gp] = Githome.Members.get_owner_by_group(group.id)%>
                        <% user = Githome.Users.get_user!(gp.uid)%>
                        <tr>
                            <td>
                                <%= link group.name, to: Routes.my_group_path(@conn, :show,
                               %{"id" => group.id}), class: "btn btn-xs btn-success" %>
                            </td>
                            <td>
                                <%= user.username %>
                            </td>
                            <%= if @user.admin do %>
                            <td>
                                <p data-placement="top" data-toggle="tooltip" title="Edit">
                                    <%= link raw(~s(<span class="glyphicon glyphicon-pencil"></span>)), to: Routes.my_group_path(@conn, :edit, %{"id" => group.id}),
                                    method: "post", target: "_blank", class: "btn btn-primary btn-xs" %>
                                </p>
                            </td>
                            <td>
                                <p data-placement="top" data-toggle="tooltip" title="Delete">
                                    <%= link raw(~s(<span class="glyphicon glyphicon-trash"></span>)), to: Routes.my_group_path(@conn, :delete, %{"id" => group.id}),
                                    method: "post", target: "_blank", class: "btn btn-danger btn-xs" %>
                                </p>
                            </td>
                            <% end %>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

apps/githome_web/lib/githome_web/templates/group/new.html.eex
<hr>
<div class="container bootstrap snippet">
    <div class="row">
        <div class="col-sm-9">
            <h1>New Group</h1>
        </div>
    </div>
    <div class="row">
        <%= render "form.html", Map.put(assigns, :action, Routes.group_path(@conn, :create)) %>
    </div>
</div>

apps/githome_web/lib/githome_web/templates/group/show.html.eex
<h1>Show Group</h1>

<ul>

    <li>
        <strong>Name:</strong>
        <%= @group.name %>
    </li>

    <li>
        <strong>Uid:</strong>
        <%= @group.uid %>
    </li>

    <li>
        <strong>Pid:</strong>
        <%= @group.pid %>
    </li>

</ul>

<span>
    <%= link "Edit", to: Routes.group_path(@conn, :edit, @group) %></span>
<span>
    <%= link "Back", to: Routes.group_path(@conn, :index) %></span>