apps/githome_web/lib/githome_web/router.ex
defmodule GithomeWeb.Router do
  use GithomeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NavigationHistory.Tracker
  end

  pipeline :verify do
    plug GithomeWeb.CheckAuth, :verify
  end

  pipeline :main_layout do
    plug :put_layout, {GithomeWeb.LayoutView, :main}
  end

  pipeline :reg_layout do
    plug :put_layout, {GithomeWeb.LayoutView, :reg}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GithomeWeb do
    pipe_through ~w[browser reg_layout]a

    get "/", LoginController, :index
    post "/login", LoginController, :login
    post "/register", LoginController, :register
  end

  scope "/session", GithomeWeb do
    pipe_through ~w[browser verify]a

    get "/new", SessionController, :new
    get "/logout", SessionController, :logout
  end

  scope "/my_projects", GithomeWeb do
    pipe_through ~w[browser main_layout verify]a

    get "/", MyProjectController, :index
    get "/new", MyProjectController, :new
    get "/show", MyProjectController, :show
    get "/edit", MyProjectController, :edit
    get "/view", MyProjectController, :view
    get "/log", MyProjectController, :log
    delete "/delete", MyProjectController, :delete
    post "/create", MyProjectController, :create
    post "/update", MyProjectController, :update
    put "/update", MyProjectController, :update
  end

  scope "/users", GithomeWeb do
    pipe_through ~w[browser main_layout verify]a

    get "/", UserController, :index
    get "/show", UserController, :show
    get "/edit", UserController, :edit
    delete "/delete", UserController, :delete
    get "/new", UserController, :new
    post "/create", UserController, :create
    post "/update", UserController, :update
    put "/update", UserController, :update
    get "/change_password", UserController, :change_password
    post "/change_password", UserController, :change_password_post
    post "/change_admin", UserController, :admin
  end

  scope "/settings", GithomeWeb do
    pipe_through ~w[browser main_layout verify]a

    get "/", ParameterController, :index
    get "/show", ParameterController, :show
    get "/edit", ParameterController, :edit
    delete "/delete", ParameterController, :delete
    get "/new", ParameterController, :new
    post "/create", ParameterController, :create
    post "/update", ParameterController, :update
  end

  scope "/projects", GithomeWeb do
    pipe_through ~w[browser main_layout verify]a

    get "/", ProjectController, :index
    get "/show", ProjectController, :show
    get "/edit", ProjectController, :edit
    delete "/delete", ProjectController, :delete
    get "/new", ProjectController, :new
    post "/create", ProjectController, :create
    post "/update", ProjectController, :update
  end

  scope "/groups", GithomeWeb do
    pipe_through ~w[browser main_layout verify]a

    get "/", GroupController, :index
    get "/show", GroupController, :show
    get "/edit", GroupController, :edit
    delete "/delete", GroupController, :delete
    get "/new", GroupController, :new
    post "/create", GroupController, :create
    post "/update", GroupController, :update
  end

  scope "/my_groups", GithomeWeb do
    pipe_through ~w[browser main_layout verify]a

    get "/", MyGroupController, :index
    get "/show", MyGroupController, :show
    get "/edit", MyGroupController, :edit
    delete "/delete", MyGroupController, :delete
    get "/new", MyGroupController, :new
    post "/create", MyGroupController, :create
    post "/update", MyGroupController, :update
    put "/update", MyGroupController, :update
  end

  #   Other scopes may use custom stacks.
  scope "/api", GithomeWeb do
    pipe_through ~w[api]a
    resources "/", ApiController
  end
end

apps/githome_web/lib/githome_web/views/layout_view.ex
defmodule GithomeWeb.LayoutView do
  use GithomeWeb, :view
end

apps/githome_web/lib/githome_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Githome</title>
</head>

<body>
    <%= render @view_module, @view_template, assigns %>
</body>

</html>

apps/githome_web/lib/githome_web/templates/layout/main.html.eex
<!DOCTYPE html>
<html>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
<!------ Include the above in your HEAD tag ---------->
<script type="text/javascript">
    function show_snackbar_noti() {
        // Get the snackbar DIV
        var x = document.getElementById("snackbar");
        // Add the "show" class to DIV
        if (x.textContent) {
            x.className = "show";

            // After 3 seconds, remove the show class from DIV
            setTimeout(function () {
                x.className = x.className.replace("show", "");
            }, 3000);
        }
    }
    window.onload = show_snackbar_noti;
</script>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Githome</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/style.css") %>"/>
</head>

<body>
    <div class="navbar-wrapper">
        <div class="container-fluid">
            <nav class="navbar navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                            aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/my_projects">GitHome</a>
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="<%= if @nav_active in [:projects, :projects_view_all, :projects_add_new, :projects_view_my]  do %> active <% else %> <% end %>dropdown">
                                <a href="#" class="dropdown-toggle " data-toggle="dropdown" role="button" aria-haspopup="true"
                                    aria-expanded="false">Projects<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li class="<%= if @nav_active == :projects_view_all do %> active <% else %> <% end %>">
                                        <a href="/projects">View All</a>
                                    </li>
                                    <li class="<%= if @nav_active == :projects_view_my do %> active <% else %> <% end %>">
                                        <a href="/my_projects">View My</a>
                                    </li>
                                    <li class="<%= if @nav_active == :projects_add_new do %> active <% else %> <% end %>">
                                        <a href="/my_projects/new">Add New</a>
                                    </li>
                                </ul>
                            </li>

                            <li class="<%= if @nav_active == :users do %> active <% else %> <% end %>"><a href="/users"
                                    class="">Users</a></li>

                            <li class="<%= if @nav_active in [:groups, :groups_view_all, :groups_add_new, :groups_view_my]  do %> active <% else %> <% end %>dropdown">
                                <a href="#" class="dropdown-toggle " data-toggle="dropdown" role="button" aria-haspopup="true"
                                    aria-expanded="false">Groups<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li class="<%= if @nav_active == :groups_view_all do %> active <% else %> <% end %>">
                                        <a href="/groups">View All</a>
                                    </li>
                                    <li class="<%= if @nav_active == :groups_view_my do %> active <% else %> <% end %>">
                                        <a href="/my_groups">View My</a>
                                    </li>
                                    <li class="<%= if @nav_active == :groups_add_new do %> active <% else %> <% end %>">
                                        <a href="/my_groups/new">Add New</a>
                                    </li>
                                </ul>
                            </li>

                            <%= if @user.admin do %>
                            <li class="<%= if @nav_active == :settings do %> active <% else %> <% end %>"><a href="/settings">Settings</a></li>
                            <% end %>

                        </ul>
                        <ul class="nav navbar-nav pull-right">
                            <li class="<%= if @nav_active in [:user_menu, :user_change_pass, :user_my_profile] do %> active <% else %> <% end %> nav-item dropdown  user-menu">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="navbarDropdownMenuLink"
                                    role="button" aria-haspopup="true" aria-expanded="false">
                                    <img class="user-image" src="<%= if @user.avatar_uri do %> <%= @user.avatar_uri %> <% else %>/images/user_default_avatar.png<% end %>"
                                        alt="User Image" style="width: 18px;" />
                                    <span>
                                        <%= @user.username %></span>
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="<%= if @nav_active == :user_change_pass do %> active <% else %> <% end %>"><a
                                            href="/users/change_password">Change Password</a></li>
                                    <li class="<%= if @nav_active == :user_my_profile do %> active <% else %> <% end %>">
                                        <%= link "My Profile", to: Routes.user_path(@conn, :show, %{"id" => @user.id }) %>
                                    </li>
                                </ul>
                            </li>
                            <li class=""><a href="/session/logout">Logout</a></li>
                        </ul>
                    </div>
                </div>
                <div class="main-frame">
                    <%= render @view_module, @view_template, assigns %>
                </div>
            </nav>
        </div>
    </div>
</body>

</html>

apps/githome_web/lib/githome_web/templates/layout/reg.html.eex
<!DOCTYPE html>
<html lang="en">

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
<!------ Include the above in your HEAD tag ---------->

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Githome</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/style.css") %>"/>
</head>
<script type="text/javascript">
    function show_snackbar_noti() {
        // Get the snackbar DIV
        var x = document.getElementById("snackbar");
        // Add the "show" class to DIV
        if (x.textContent) {
            x.className = "show";

            // After 3 seconds, remove the show class from DIV
            setTimeout(function () {
                x.className = x.className.replace("show", "");
            }, 3000);
        }
    }
    window.onload = show_snackbar_noti;
</script>

<body>
    <div class="navbar-wrapper">
        <div class="container-fluid">
            <nav class="navbar navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                            aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand">GitHome</a>
                    </div>
                </div>
                <div class="main-frame">
                    <%= render @view_module, @view_template, assigns %>
                </div>
            </nav>
        </div>
    </div>
</body>

</html>